git:
  depth: 10
notifications:
  email: false
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/?insertMode=update'
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never

before_install:
  - export BOTO_CONFIG=/dev/null

language: node_js
node_js:
  - "4"
os:
  - linux
  - osx
env:
  - TARGET_ARCH=x64
osx_image: xcode7.3

matrix:
  include:
    - os: linux
      env: TARGET_ARCH=arm
    - os: linux
      env: TARGET_ARCH=ia32
    - os: linux
      env: TARGET_ARCH=arm64
  allow_failures:
    - os: osx

script: './script/cibuild'

branches:
  only:
    - master
